name: Publish to PyPI
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g. 1.2.59)'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      # Required for trusted publishing
      id-token: write
      contents: write  # Changed to write to allow tag creation

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel build bump2version
          
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Update version and create tag
        run: |
          bump2version --new-version ${{ inputs.version }} --allow-dirty patch
          git push
          git push --tags
          
      - name: Build package
        run: |
          rm -rf build/ dist/
          python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1