name: Publish to PyPI
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g. 1.2.68)'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write  # Required for trusted publishing

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel build bump2version

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Update version
        run: |
          bump2version --new-version ${{ inputs.version }} --allow-dirty patch --no-tag

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: release-${{ inputs.version }}
          base: main
          title: 'Release version ${{ inputs.version }}'
          body: 'Automated release of version ${{ inputs.version }}.'
          labels: 'automated release'

      # The following steps will be executed after the PR is merged
      - name: Build package
        if: github.event_name == 'workflow_dispatch'
        run: |
          rm -rf build/ dist/
          python -m build

      - name: Publish package to PyPI
        if: github.event_name == 'workflow_dispatch'
        uses: pypa/gh-action-pypi-publish@release/v1