name: Publish to PyPI
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g. 1.2.59)'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write  # Added permission to create pull requests
      id-token: write       # Required for trusted publishing

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel build bump2version

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create new branch
        run: |
          git checkout -b release-${{ inputs.version }}

      - name: Update version and create tag
        run: |
          bump2version --new-version ${{ inputs.version }} --allow-dirty patch
          git push --set-upstream origin release-${{ inputs.version }}
          git push --tags

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: release-${{ inputs.version }}
          title: 'Release version ${{ inputs.version }}'
          body: 'Automated release of version ${{ inputs.version }}.'
          labels: 'automated release'

      - name: Build package
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        run: |
          rm -rf build/ dist/
          python -m build

      - name: Publish package to PyPI
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: pypa/gh-action-pypi-publish@release/v1